### ISSUE TITLE
Missing unicode dependency

### ISSUE THREAD

**Issue by Gjum** [andrewrk/genesis#8]
When building on Arch Linux, I get these errors:

`master` branch:
```sh
gcc -o build/generate_unicode_data build/generate_unicode_data.o build/util.o build/byte_buffer.o
make: *** No rule to make target '/usr/share/unicode/UnicodeData.txt', needed by 'build/unicode.hpp'.  Stop.
```

`pipeline` branch:
```
  The dependency target "/home/gjum/src/genesis/build/unicode.hpp" of target
  "genesis" does not exist.
```
[Full error log here](https://gist.github.com/Gjum/b91bb153a7038cee5759).

Seems like my system is missing some `UnicodeData.txt` file. Any idea which package might provide it? It's quite difficult to find just by its filename without diving into the code.
Should also possibly be added to the dependencies.

Great project, I would be really happy to try it out.

**Comment by andrewrk** [comment]
I love your enthusiasm, but it's simply too early! Come back in 4 months and there will be something worth checking out. If you *really* want to get it working right now, you can download this file: ftp://ftp.unicode.org/Public/UNIDATA/UnicodeData.txt  put it anywhere on your hard drive, and then change "/usr/share/unicode/UnicodeData.txt" to your file path in CMakeLists.txt.

If you just watched the youtube video, I've been working in the `pipeline` branch, in which I have a basic synthesizer working, but the main project doesn't build until I rewrite it to use the new internal API.

**Comment by Gjum** [comment]
Thanks! Now that that's working, other things start to break. :D I'm out, see you in 4 months!
